### ISSUE TITLE
【开源自荐】yft-design：基于Canvas的开源版"创客贴"

### ISSUE THREAD

**Issue by more-strive** [opendigg/awesome-github-vue#38]
项目名称：yft-design

项目地址：https://github.com/dromara/yft-design

项目Demo: https://more-strive.github.io/design/
国内体验：https://yft.design

项目简介 (100 字以内)：使用 Vue3 + TypeScript + Fabric.js + Pinia + Element-Plus，支持 文字、图片、形状、线条、二维码 、条形码几种最常用的元素类型，每一种元素都拥有高度可编辑能力，缩略图显示，模板，支持导出json，svg, image文件
![image](https://github.com/opendigg/awesome-github-vue/assets/113762408/7e442e4a-5a68-4510-affc-9a4bd54e014e)
![image](https://github.com/opendigg/awesome-github-vue/assets/113762408/0e1ae1b1-fb17-4b57-9671-b9ba5e6ca65a)

**Comment by Bryce-come** [comment]
这是来自QQ邮箱的假期自动回复邮件。我已收到您的来信并将尽快回复。祝您工作顺利，生活愉快！Thanks for your email!I will respond to you at the first time!
