### ISSUE TITLE
vue-js-toggle-button

### ISSUE THREAD

**Issue by euvl** [opendigg/awesome-github-vue#4]
Hey guys, could you please add `vue-js-toggle-button` to the list (i do not speak Chinese 😞)

URL: http://vue-js-toggle-button.yev.io/
Repo: https://github.com/euvl/vue-js-toggle-button/
Description: Vue.js 2.0+ toggle / switch button - simple, pretty, customizable, 0 deps.

**Comment by youlong723687543** [comment]
good
